### ISSUE TITLE
Cannot find implementation for FindFeatures, FindFaces, Find

### ISSUE THREAD

**Issue by Agreema** [Ajay191191/Opencv-Face-Recognition#3]
Hi,

I am trying your project but i m stuck with an error:

Cannot resolve corresponding jni function : 
public native void FindFeatures(int width, int height, byte yuv[], int[] rgba);
    public native void FindFaces(String imageName,String FileName);
    public native int Find(String imageName,String FileName,String Csv);

I am getting this error for these three methods.
When i click on "Take Picture" the app crashes with the following log

03-06 23:08:59.481 19590-19949/fcuocv.com.opencvtest E/art: No implementation found for void fcuocv.com.opencvtest.Sample3View.FindFeatures(int, int, byte[], int[]) (tried Java_fcuocv_com_opencvtest_Sample3View_FindFeatures and Java_fcuocv_com_opencvtest_Sample3View_FindFeatures__II_3B_3I)
03-06 23:08:59.485 19590-19590/fcuocv.com.opencvtest D/Camera-JNI: Adding callback buffer to queue, 1 total
03-06 23:08:59.487 19590-19949/fcuocv.com.opencvtest E/AndroidRuntime: FATAL EXCEPTION: Thread-22755
                                                                       Process: fcuocv.com.opencvtest, PID: 19590
                                                                       java.lang.UnsatisfiedLinkError: No implementation found for void fcuocv.com.opencvtest.Sample3View.FindFeatures(int, int, byte[], int[]) (tried Java_fcuocv_com_opencvtest_Sample3View_FindFeatures and Java_fcuocv_com_opencvtest_Sample3View_FindFeatures__II_3B_3I)
                                                                           at fcuocv.com.opencvtest.Sample3View.FindFeatures(Native Method)
                                                                           at fcuocv.com.opencvtest.Sample3View.processFrame(Sample3View.java:64)
                                                                           at fcuocv.com.opencvtest.SampleViewBase.run(SampleViewBase.java:192)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by miawoltn** [comment]
Hi
,you have to modify the  c++ functions in your jni folder to have your app package as prefix.
For example:
 if your package name is
  com.mycompany.myapp
 then the FindFeatures function should look like
  Java_com_mycompany_myapp_classname_FindFeatures
